---
- hosts: nodes
  vars:
    service:
     - httpd
     - firewalld
  tasks:
  - name: Install httpd and firewalld
    yum: 
      name: "{{ service }}"
      state: latest
    with_items: "{{ service }}"
  - name: Enable httpd and firewalld services
    service:
      name: "{{ service }}"
      enabled: yes
      state: started
    with_items: "{{ service }}"
  - name: Check firewalld service
    service_facts:
    - debug:
      var: ansible_facts.services["firewalld.service"]
  - name: Check httpd service
    service_facts:
    - debug:
      var: ansible_facts.services["httpd.service"]
  - name: Create index.html
    lineinfile:
      path: /var/www/html/index.html
      line: "Welcome to my web server"
      create: yes
  - name: Open http
    firewalld:
      service: http
      permanent: yes
      state: enabled
      immediate: yes
  - name: Open https
    firewalld:
      service: https
      permanent: yes
      state: enabled
      immediate: yes
